# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Glasse-age
author: Ranats
email: Coda@hope.tokai-u.jp
description: 覚え書きブログ - グラサージュ
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ranats.github.io" # the base hostname & protocol for your site
twitter_username: Rantas85
github_username:  Ranats

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#  extensions: [tables,autolink,strikethrough,fenced_code_blocks]
markdown: kramdown
kramdown:
        input: GFM
        hard_wrap: false
        enable_coderay: false
        syntax_highlighter: rouge
        #highlighter: rouge
#    syntax_highlighter_opts:

        #highlighter: pygments
#highlighter: false
#pygments_options: ['lineanchors', 'linenos']


gems: [jekyll-paginate]

# the number of post per page
paginate: 5
paginate_path: "blog/page:num"
